const QRCode = require('qrcode');
const fs = require('fs');

module.exports = {
    name: 'qrcode',
    description: 'Generate QR code from text or URL',
    aliases: ['qr', 'qrgen', 'generateqr'],
    async execute(sock, message, args, { isOwner, settings }) {
        const from = message.key.remoteJid;

        if (!args[0]) {
            return await sock.sendMessage(from, { 
                text: `❌ *Enter text or URL to generate QR code*\n\nExample: ${settings.prefix}qr https://google.com\n${settings.prefix}qr Hello World` 
            }, { quoted: message });
        }

        const text = args.join(' ');
        const processingMsg = await sock.sendMessage(from, { 
            text: '🔲 Generating QR code...' 
        }, { quoted: message });

        try {
            // Create temp directory if it doesn't exist
            const tempDir = './temp';
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }

            const qrPath = `./temp/qr_${Date.now()}.png`;

            // Generate QR code
            await QRCode.toFile(qrPath, text, {
                width: 512,
                margin: 2,
                color: {
                    dark: '#000000',
                    light: '#FFFFFF'
                }
            });

            await sock.sendMessage(from, { delete: processingMsg.key });

            // Send QR code image
            await sock.sendMessage(from, {
                image: fs.readFileSync(qrPath),
                caption: `🔲 *QR Code Generated*\n\n📝 *Content:* ${text.length > 100 ? text.substring(0, 100) + '...' : text}\n\n🤖 Generated by ${settings.botName}`
            }, { quoted: message });

            // Clean up
            if (fs.existsSync(qrPath)) {
                fs.unlinkSync(qrPath);
            }

            console.log("QR code generated and sent successfully");

        } catch (error) {
            console.log("QR code generation error:", error);
            
            await sock.sendMessage(from, { delete: processingMsg.key });
            
            await sock.sendMessage(from, { 
                text: `❌ *Failed to generate QR code*\n\n🔧 Please try again with different text or check if the content is valid.` 
            }, { quoted: message });
        }
    }
};